### ISSUE TITLE
Bug: Settings ("Dark Mode") not persisted

### ISSUE THREAD

**Issue by sondreb** [StampChat/stamp#404] opened 2021-08-08 17:46 UTC
I changed to "Dark Mode" in settings on first launch and setup, when I fully exit Stamp and open again, it renders in "Light Mode".

**Comment by schancel** [comment] 2021-11-10 16:29
@wiktorcie Is this an issue for you?

**Comment by wiktorcie** [comment] 2021-11-13 09:21
Which build is this about? Windows / Mac / PWA? I checked on electron-ubuntu and it works there as intended.

**Comment by schancel** [comment] 2022-06-19 19:38
Should be fixed now.

**Closed by schancel** 2022-06-19 19:38 UTC
Labels: bug
